
name: Machine Learning CI

# Workflow ini akan berjalan setiap kali Anda melakukan 'push' ke branch main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode dari repository GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Menyiapkan Python versi 3.12.7
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Menginstal library yang dibutuhkan
      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas

      # 4. Menjalankan MLflow Project
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --no-conda
